### ISSUE TITLE
Data format

### ISSUE THREAD

**Issue by gogoARS** [celiahacker/k-simplex2vec#1]
Hi Celia, nice work on the simplicial complex embedding and thanks for sharing the codes! I wonder if you could provide any example of the input data? That would be really helpful. Thank you!

**Comment by celiahacker** [comment]
Hi! Sorry for the long response time... I've just added a jupyter notebook where you can see an example. The input data should be a gudhi simplex tree, which was built from a graph in this example. I hope this helps :)
Don't hesitate to contact me if something is not clear

**Comment by gogoARS** [comment]
> Hi! Sorry for the long response time... I've just added a jupyter notebook where you can see an example. The input data should be a gudhi simplex tree, which was built from a graph in this example. I hope this helps :)
> Don't hesitate to contact me if something is not clear

Thank you! This is really helpful.
